//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avance
    {
        public int CodeAvance { get; set; }
        public int RefCommande { get; set; }
        public decimal Montant { get; set; }
        public System.DateTime DateAvance { get; set; }
        public int CodeModeReglement { get; set; }
        public string Note { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual ModeReglement ModeReglement { get; set; }
    }
}
