//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonLivraison
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BonLivraison()
        {
            this.DetailsBLs = new HashSet<DetailsBL>();
        }
    
        public string CodeBL { get; set; }
        public int RefCommande { get; set; }
        public System.DateTime DateBL { get; set; }
        public decimal TotalHT { get; set; }
        public decimal TotalTTC { get; set; }
        public string NomCommercial { get; set; }
        public decimal Remise { get; set; }
    
        public virtual Commande Commande { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsBL> DetailsBLs { get; set; }
    }
}
