//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Commandes = new HashSet<Commande>();
            this.ReceptionSemences = new HashSet<ReceptionSemence>();
        }
    
        public int CodeClient { get; set; }
        public string Libelle { get; set; }
        public string Responsable { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> CodePostal { get; set; }
        public string Ville { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public Nullable<int> CIN { get; set; }
        public string NomCommercial { get; set; }
        public Nullable<int> CodeTVA { get; set; }
        public Nullable<int> CodeBanque { get; set; }
        public Nullable<int> RIB { get; set; }
        public string SiteWeb { get; set; }
        public Nullable<int> CodeTypeClient { get; set; }
        public Nullable<int> CodePointVente { get; set; }
        public Nullable<int> Timbre { get; set; }
        public string RegTVA { get; set; }
        public Nullable<decimal> PlafondCredit { get; set; }
        public Nullable<decimal> PlafondEnCours { get; set; }
        public string Tarif { get; set; }
    
        public virtual Banque Banque { get; set; }
        public virtual PointVente PointVente { get; set; }
        public virtual TypeClient TypeClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceptionSemence> ReceptionSemences { get; set; }
    }
}
