//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClotureCommande
    {
        public string CodeClotureCommande { get; set; }
        public int RefCommande { get; set; }
        public System.DateTime DateClotureCommande { get; set; }
    
        public virtual Commande Commande { get; set; }
    }
}
