//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comptage
    {
        public int CodeComptage { get; set; }
        public int CodeProduction { get; set; }
        public string CodeUtilisateur { get; set; }
        public string Libelle { get; set; }
        public System.DateTime DateCompatage { get; set; }
        public int QuantiteComptage { get; set; }
        public int TypeComptage { get; set; }
    
        public virtual TypeComptage TypeComptage1 { get; set; }
        public virtual Production Production { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
