//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailsBL()
        {
            this.MouvementStocks = new HashSet<MouvementStock>();
        }
    
        public string CodeDetailsBL { get; set; }
        public string CodeBL { get; set; }
        public System.DateTime DateLivraison { get; set; }
        public decimal MntBrutHT { get; set; }
        public decimal MntRemise { get; set; }
        public decimal MntNETHT { get; set; }
        public decimal TVA { get; set; }
        public decimal MntNetTTC { get; set; }
    
        public virtual BonLivraison BonLivraison { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MouvementStock> MouvementStocks { get; set; }
    }
}
