//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsCommande
    {
        public int RefDetailsCommande { get; set; }
        public int CodeVariete { get; set; }
        public int RefCommande { get; set; }
        public System.DateTime DateLivraisonPrevu { get; set; }
        public decimal MntBrutHT { get; set; }
        public decimal Remise { get; set; }
        public decimal MntRemise { get; set; }
        public decimal MntNETHT { get; set; }
        public decimal TVA { get; set; }
        public decimal MntNETTTC { get; set; }
        public decimal PrixUnitaire { get; set; }
        public decimal PrixUnitaireNet { get; set; }
        public decimal TotalBrut { get; set; }
        public decimal TotalBrutNet { get; set; }
        public string ReservationCons { get; set; }
        public int CodeReception { get; set; }
        public decimal Accompte { get; set; }
        public decimal Brut { get; set; }
        public decimal Timbre { get; set; }
        public decimal RemiseTot { get; set; }
        public decimal Net { get; set; }
        public int CodeSupport { get; set; }
        public int CodeTypeProd { get; set; }
        public System.DateTime DateCV { get; set; }
        public System.DateTime DateCG { get; set; }
        public System.DateTime DatePG { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual ReceptionSemence ReceptionSemence { get; set; }
        public virtual Support Support { get; set; }
        public virtual TypeProduction TypeProduction { get; set; }
        public virtual Variete Variete { get; set; }
    }
}
