//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactureConsigne
    {
        public int CodeFacture { get; set; }
        public Nullable<System.DateTime> DateFacture { get; set; }
        public Nullable<int> CodeFourniseur { get; set; }
        public int CodeSupport { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<decimal> PUht { get; set; }
        public Nullable<decimal> PuTTC { get; set; }
        public Nullable<decimal> Remise { get; set; }
        public Nullable<decimal> FodecArticle { get; set; }
        public Nullable<decimal> TVA { get; set; }
        public Nullable<decimal> Ht { get; set; }
        public Nullable<decimal> TTC { get; set; }
        public Nullable<decimal> MntRemise { get; set; }
        public Nullable<decimal> Timbre { get; set; }
        public Nullable<decimal> NetTTc { get; set; }
        public Nullable<decimal> NetHt { get; set; }
        public Nullable<decimal> TotRemise { get; set; }
        public Nullable<decimal> TotHt { get; set; }
        public Nullable<decimal> TotFodec { get; set; }
        public Nullable<decimal> TotTva { get; set; }
        public Nullable<int> PointdeVente { get; set; }
    
        public virtual Fourniseur Fourniseur { get; set; }
        public virtual PointVente PointVente { get; set; }
        public virtual Support Support { get; set; }

        public string LibelleSupport
        {
            get
            {
                return Support.Libelle;


            }
        }
        public int CodeSup
        {
            get
            {
                return Support.CodeSupport;


            }

        }
        public string Libelle
        {
            get
            {
                return PointVente.Libelle;
            }


        }
        public string NomFourniseur
        {
            get
            {
                return Fourniseur.NomFourniseur;
            }


        }
    }
}
