//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FonctionMenu
    {
        public int CodeFonction { get; set; }
        public string LibelleFonction { get; set; }
        public Nullable<int> CodeMenu { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
