//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrageProduction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParametrageProduction()
        {
            this.Productions = new HashSet<Production>();
        }
    
        public int CodeParProduction { get; set; }
        public int Capacite { get; set; }
        public int RappelLivraison { get; set; }
        public int RappelSemis { get; set; }
        public int RappelSemisPorte { get; set; }
        public int RappelGreffage { get; set; }
    
        public virtual ParametrageProduction ParametrageProduction1 { get; set; }
        public virtual ParametrageProduction ParametrageProduction2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Productions { get; set; }
    }
}
