//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptionSemence
    {
        public int CodeReceptionSemence { get; set; }
        public int RefCommande { get; set; }
        public int CodeSemence { get; set; }
        public int CodeClient { get; set; }
        public string Note { get; set; }
        public System.DateTime DateProduction { get; set; }
        public decimal Qte { get; set; }
        public int CodeUnite { get; set; }
        public int CodeColisage { get; set; }
        public int Nbrgraines { get; set; }
        public int Nlot { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Colisage Colisage { get; set; }
        public virtual Commande Commande { get; set; }
        public virtual Semence Semence { get; set; }
        public virtual Unite Unite { get; set; }
    }
}
