//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptionSemence
    {
        public string CodeReceptionSemence { get; set; }
        public int RefCommande { get; set; }
        public int CodeSemence { get; set; }
        public string TypeTiers { get; set; }
        public string Etat { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Semence Semence { get; set; }
    }
}
