//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Semence()
        {
            this.ReceptionSemences = new HashSet<ReceptionSemence>();
        }
    
        public int CodeSemence { get; set; }
        public int CodeSemencier { get; set; }
        public string Libelle { get; set; }
        public int NBGraines { get; set; }
        public Nullable<int> CodeEspece { get; set; }
    
        public virtual Espece Espece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceptionSemence> ReceptionSemences { get; set; }
        public virtual Semencier Semencier { get; set; }
    }
}
