//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Serre()
        {
            this.Productions = new HashSet<Production>();
        }
    
        public int CodeSerre { get; set; }
        public int CodeEmplacement { get; set; }
        public decimal Superficier { get; set; }
        public decimal Capacite { get; set; }
    
        public virtual Emplacement Emplacement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Productions { get; set; }

        public string Libelle
        {
            get
            {
                return Emplacement.Libelle;
            }


        }
    }
}
