//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Societe
    {
        public int CodeSociete { get; set; }
        public string LibelleFr { get; set; }
        public string VilleFr { get; set; }
        public int CodePostal { get; set; }
        public string Tel { get; set; }
        public string Banque { get; set; }
        public string RIB { get; set; }
        public string Activite { get; set; }
        public string Responsable { get; set; }
        public string SiteWeb { get; set; }
        public string AdresseFr { get; set; }
        public string Fax { get; set; }
        public string MF { get; set; }
        public string CodeD { get; set; }
        public string RegCom { get; set; }
        public string Fonction { get; set; }
        public string Email { get; set; }
        public string LibelleAr { get; set; }
        public string AdresseAr { get; set; }
        public string VilleAr { get; set; }
    }
}
