//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortieConsigne
    {
        public int NumeroSortie { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public Nullable<int> CodeLivreur { get; set; }
        public Nullable<int> CodePointVente { get; set; }
        public Nullable<int> CodeMoyenTransport { get; set; }
        public string Note { get; set; }
        public Nullable<int> CodeSupport { get; set; }
        public Nullable<int> Qte { get; set; }
        public Nullable<decimal> PrixTot { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> PrixUnit { get; set; }
    
        public virtual Livreur Livreur { get; set; }
        public virtual MoyenTransport MoyenTransport { get; set; }
        public virtual PointVente PointVente { get; set; }
        public virtual Support Support { get; set; }

        public string LibellePointVente
        {
            get
            {
                return PointVente.Libelle;


            }
        }

        public string LibelleMoyenTrans
        {
            get
            {
                return MoyenTransport.Libelle;


            }
        }
        public string LibelleLivreur
        {
            get
            {
                return Livreur.Libelle;


            }
        }
    }
}
