//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Support()
        {
            this.Commandes = new HashSet<Commande>();
            this.MouvementStocks = new HashSet<MouvementStock>();
        }
    
        public int CodeSupport { get; set; }
        public string Libelle { get; set; }
        public string Matiere { get; set; }
        public int Dimension { get; set; }
        public int NbrAlv { get; set; }
        public int VolAlv { get; set; }
        public decimal Poids { get; set; }
        public decimal PrixAchatHT { get; set; }
        public decimal PrixAchatTTC { get; set; }
        public decimal PrixVenteHT { get; set; }
        public decimal PrixVenteTTC { get; set; }
        public double Marge { get; set; }
        public double TVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MouvementStock> MouvementStocks { get; set; }
    }
}
