//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Support()
        {
            this.Commandes = new HashSet<Commande>();
            this.FactureConsignes = new HashSet<FactureConsigne>();
            this.MouvementStocks = new HashSet<MouvementStock>();
            this.SortieConsignes = new HashSet<SortieConsigne>();
        }
    
        public int CodeSupport { get; set; }
        public string Libelle { get; set; }
        public string Matiere { get; set; }
        public Nullable<int> Dimension { get; set; }
        public Nullable<int> NbrAlv { get; set; }
        public Nullable<int> VolAlv { get; set; }
        public Nullable<decimal> Poids { get; set; }
        public Nullable<decimal> PrixAchatHT { get; set; }
        public Nullable<decimal> PrixAchatTTC { get; set; }
        public Nullable<decimal> PrixVenteHT { get; set; }
        public Nullable<decimal> PrixVenteTTC { get; set; }
        public Nullable<double> Marge { get; set; }
        public Nullable<double> TVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactureConsigne> FactureConsignes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MouvementStock> MouvementStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SortieConsigne> SortieConsignes { get; set; }

        public string codeLibelle
        {
            get
            {
                return CodeSupport + ":" + Libelle;
            }
        }
    }
}
