//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlant.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Variete()
        {
            this.Commandes = new HashSet<Commande>();
        }
    
        public int CodeVariete { get; set; }
        public int CodeEspece { get; set; }
        public string LibelleVariete { get; set; }
        public int CodeTypeProd { get; set; }
        public int NBjoursCV { get; set; }
        public int NBjoursCG { get; set; }
        public int NBjoursPG { get; set; }
        public decimal Marge { get; set; }
        public decimal MontantMarge { get; set; }
        public decimal PrixVente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commandes { get; set; }
        public virtual Espece Espece { get; set; }
        public virtual TypeProduction TypeProduction { get; set; }
    }
}
